#!/bin/bash

PID_FILE=/tmp/i3rest.pid

BASE=10
if [[ $# != 0 ]]; then
    BASE=$1
fi
LOCK_AFTER="$((${BASE} * 60))"

function wait_and_lock() {
    echo "lock after ${BASE}m"

    sleep $LOCK_AFTER && \
        i3lock -c c442f0
}

kill $(cat ${PID_FILE} 2> /dev/null) >> /dev/null 2>&1

wait_and_lock &
echo $! > ${PID_FILE}
